trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: '$(acrServiceConnection)'
  imageRepository: 'app'
  containerRegistry: '$(dockerRegistryServiceConnection).azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        command: 'buildAndPush'
        repository: '$(containerRegistry)/$(imageRepository)'
        Dockerfile: 'App/Dockerfile'
        tags: |
          $(tag)
    
- stage: Deploy
  dependsOn: Build
  jobs:
    - job: Deploy
      steps:
        - task: AzureWebAppContainer@1
          inputs:
            azureSubscription: $(azureSubscription)
            appName: $(appServiceName)
            resourceGroupName: $(resourceGroupName)
            imageName: '$(containerRegistry)/$(imageRepository):$(tag)'
